### PR TITLE
Update to python3

### PR DESCRIPTION
**Pull request by exowanderer**
I could only use pynrc from the github directory, because if I left the github directory and used `import pynrc`,  I found ImportErrors and a few others (see below):

1) `ImportError nrc_utils does not exist` and `ImportError pynrc_core does not exist`
2) `Dictionary does not have attribute 'has_key'`
3) `print statement lacked parenthesis`

solution 1) I went through all of the files that generated an error (about 5) that were generated and fixed the import statements. 

solution 2) I received an independent error while trying `import pynrc` in file "nrc_utils.py" on `line 58`.  This file asked for `d.has_key(+key_name+)`, which is an outdated usage. So I changed it to read `+key_name+ in d.keys()`

solution 3) Similarly, in file "robust.py" on `line 235`, there was a python2 print statement that I changed to a python3 print statement.

### CODE REVIEW

**Comment by JarronL** [comment]
Are you have to get pynrc to play nicely with Python 3? I haven't tried yet.

**Comment by JarronL** [comment]
Also: Yay! for successfully merging a pull request!

**Comment by exowanderer** [comment]
Yes. I only use python3 now and these edits let me use `pynrc` in python3. I have not yet had any issues beyond this merge.

PS: I don't know how to set a PR to anything but `master`. Do you know how? Was this PR appropriate? Thanks :)

**Comment by JarronL** [comment]
Great! Glad to hear Python 3 is working so far. That will give me some
encouragement to switch over. I should probably just add another conda
environment with Python 3 to test various aspects as things progress. I'm
pretty sure that are some differences when it comes to subclassing, which
might break my current development in obs_nircam.py.

You're right, I don't have any branches other than the master. Is it more
appropriate for me to have a development branch that only gets committed to
master after careful vetting? Still haven't quite gotten the hang of best
git practices.

**Pull request merged**
